#!/bin/env bash

set -e

# ref: https://askubuntu.com/a/30157/8698
if ! [ $(id -u) = 0 ]; then
   echo "The script need to be run as root." >&2
   exit 1
fi

print_red() {
  echo -e "\033[0;31m$1\033[0m"
}

print_red "Installing Rust and Cargo"
curl https://sh.rustup.rs -sSf | sh


print_red "Installing Linuxbrew"
sudo apt-get install build-essential procps curl file git
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

print_red "Installing Flatpak"
sudo apt install flatpak
# Add flathub repository
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

print_red "Install AppImage launcher"
sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt-get update
sudo apt-get install appimagelauncher

print_red "Install Go"
sudo apt-get install golang
