#!/bin/bash

for i in *.avif;
do
    NEW_NAME=$(basename $i .avif)".jpg"
    ffmpeg -i "$i" "$NEW_NAME"
done

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Moving .avif files to trash."
    for i in *.avif;
    do
        trash "$i"
    done
fi
